# Generated by Django 5.0.1 on 2024-05-26 06:28

import src.general.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="General",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=255, max_length=255)),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=src.general.models.General.get_upload_path_for_logo,
                    ),
                ),
                ("is_data_updated", models.BooleanField(default=False)),
            ],
        ),
    ]
