# Generated by Django 5.0.1 on 2024-04-07 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='full_name',
            new_name='fullname',
        ),
    ]
