# Generated by Django 5.0.1 on 2024-05-26 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0002_rename_full_name_employee_fullname"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="is_attend",
            field=models.BooleanField(default=False),
        ),
    ]
